import keyMirror from 'keymirror';

export default keyMirror({
  SESSION_AUTHORIZE_REQUEST: null,
  SESSION_AUTHORIZE_SUCCESS: null,
  SESSION_AUTHORIZE_FAIL: null,

  SIGN_UP_REQUEST: null,
  SIGN_UP_SUCCESS: null,
  SIGN_UP_FAIL: null,

  CREATE_EVENT_REQUEST: null,
  CREATE_EVENT_FAIL: null,
  CREATE_EVENT_SUCCESS: null,

  CREATE_JOB_REQUEST: null,
  CREATE_JOB_FAIL: null,
  CREATE_JOB_SUCCESS: null,

  CREATE_NEWS_REQUEST: null,
  CREATE_NEWS_FAIL: null,
  CREATE_NEWS_SUCCESS: null,

  UPLOAD_IMG_REQUEST: null,
  UPLOAD_IMG_FAIL: null,
  UPLOAD_IMG_SUCCES: null,
});
